-- SESSION 1:
-- pizzeriadb=# begin transaction isolation level serializable;
-- BEGIN
-- pizzeriadb=*# select * from pizzeria where name = 'Pizza Hut'
-- ;
--  id |   name    | rating 
-- ----+-----------+--------
--   1 | Pizza Hut |    3.6
-- (1 row)
-- pizzeriadb=*# select * from pizzeria where name = 'Pizza Hut'
-- ;
--  id |   name    | rating 
-- ----+-----------+--------
--   1 | Pizza Hut |    3.6
-- (1 row)
-- pizzeriadb=*# commit;
-- COMMIT
-- pizzeriadb=# select * from pizzeria where name = 'Pizza Hut'
-- ;
--  id |   name    | rating 
-- ----+-----------+--------
--   1 | Pizza Hut |    3.0
-- (1 row)
-- SESSION 2:
-- pizzeriadb=# begin transaction isolation level serializable;
-- BEGIN
-- pizzeriadb=*# update pizzeria
-- set rating = 3.0
-- where name = 'Pizza Hut'
-- ;
-- UPDATE 1
-- pizzeriadb=*# commit;
-- COMMIT
-- pizzeriadb=# select * from pizzeria where name = 'Pizza Hut';
--  id |   name    | rating 
-- ----+-----------+--------
--   1 | Pizza Hut |    3.0
-- (1 row)